name: test

on:
  push:
    branches:
      - master # default branch
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  copy:
    runs-on: ubuntu-latest   # 一个运行代码的虚拟机
    name: fisrt demo
    steps:
      - uses: actions/checkout@v2  # git pull 将代码拉取到 ubuntu-latest 虚拟机上
      - name: Use Node.js  # 在 ubuntu-latest 虚拟机上安装 node 环境
        uses: actions/setup-node@v1
        with:
            node-version: 16    # 安装的 node 版本为 14
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:yangxiaolu1993/imonitor-vue.git
          BRANCH: master
          FOLDER: build
          SSH_PRIVATE_KEY: ${{ secrets.YANGXIAOLU }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
        
