name: test

on:
  push:
    branches:
      - cicd # default branch
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  copy:
    runs-on: ubuntu-latest   # 一个运行代码的虚拟机
    name: fisrt demo
    steps:
      - uses: actions/checkout@v2  # git pull 将代码拉取到 ubuntu-latest 虚拟机上
      - name : Deploy 
        uses : JamesIves/github-pages-deploy-action@4.1.7 
        with :
          branch : master # action 应该部署到的分支。
          folder : docs #操作应该部署的文件夹。
          repository-name: yangxiaolu1993/imonitor-vue
          token: ${{ secrets.TOKEN_SECRET }}
          target-folder: docs_copy
        
