name: test

on:
  push:
    branches:
      - master # default branch
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest   # 一个运行代码的虚拟机
    name: fisrt demo
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:yangxiaolu1993/practiceForVue.git
          destination-repo: git@github.com:yangxiaolu1993/cipher-vue.git

        
