name: test

on:
  push:
    branches:
      - master # default branch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Git Sync Resposity
    steps:
      - uses: actions/checkout@v2
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          # Such as https://github.com/wangchucheng/git-repo-sync.git
          target-url: https://github.com/yangxiaolu1993/cipher-react.git
          # Such as wangchucheng
          target-username: yangxiaolu1993
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS_TOKEN }}
          target-token: ${{ secrets.ACCESS_TOKEN }}
