name: test

on:
  push:
    branches:
      - master # default branch
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest   # 一个运行代码的虚拟机
    name: fisrt demo
    steps:
      - uses: actions/checkout@v2  # git pull 将代码拉取到 ubuntu-latest 虚拟机上
      - name: Use Node.js  # 在 ubuntu-latest 虚拟机上安装 node 环境
        uses: actions/setup-node@v1
        with:
            node-version:14    # 安装的 node 版本为 14
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          # Such as https://github.com/wangchucheng/git-repo-sync.git
          target-url: https://github.com/wangchucheng/git-repo-sync.git
          # Such as wangchucheng
          target-username: wangchucheng
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS_TOKEN }}
          target-token: ${{ secrets.ACCESS_TOKEN }}
